'use strict';
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const KEY='coach-chatty-v1';
let storageOK=true;function read(){try{return JSON.parse(localStorage.getItem(KEY))||{}}catch{return {}}}
let state=read();state.history=Array.isArray(state.history)?state.history:[];
let feedFresh=false;let plan=state.plan,library=state.library||[],equipment=state.equipment||{items:[]},draft=state.draft,view='workout',result=null,restEnd=state.restEnd||0;
function notice(t){$('#notice').textContent=t}
function save(){Object.assign(state,{plan,library,equipment,draft,restEnd});try{localStorage.setItem(KEY,JSON.stringify(state));storageOK=true}catch{storageOK=false;notice('Storage is unavailable or full. Keep this page open and download your results before leaving.')}}
function validPlan(p){if(!p||p.schemaVersion!==1||typeof p.id!=='string'||!p.id||typeof p.title!=='string'||!['kg','lb'].includes(p.unit)||!Array.isArray(p.exercises)||p.exercises.length>100)throw Error('Invalid workout');const ids=new Set();for(const e of p.exercises){if(!e.id||ids.has(e.id)||typeof e.name!=='string'||!Array.isArray(e.sets)||e.sets.length>50)throw Error('Invalid exercise');ids.add(e.id);for(const s of e.sets)for(const k of ['weight','reps'])if(s[k]!=null&&s[k]!==''&&(!Number.isFinite(Number(s[k]))||Number(s[k])<0||(k==='reps'&&!Number.isInteger(Number(s[k])))))throw Error('Invalid set')}return p}
function previous(id){for(const h of state.history){if(h.unit!==(draft?.unit||plan?.unit))continue;const e=h.exercises.find(e=>e.id===id&&!e.substitution&&e.sets.some(s=>s.done));if(e)return e.sets.filter(s=>s.done)}return null}
function exercise(e){const prior=previous(e.id)||e.prior||[];return {...e,prior,sets:e.sets.map((s,i)=>({weight:s.weight??prior[i]?.weight??'',reps:s.reps??prior[i]?.reps??'',done:false})),rpe:'',pain:'',substitution:'',notes:''}}
function fresh(){if(!plan)return;draft={sessionId:crypto.randomUUID(),planId:plan.id,revision:plan.revision??1,title:plan.title,unit:plan.unit,coachNote:plan.coachNote||'',createdAt:new Date().toISOString(),startedAt:null,notes:'',exercises:plan.exercises.map(exercise)};save()}
function count(){return draft?draft.exercises.reduce((a,e)=>a+e.sets.filter(s=>s.done).length,0):0}
function total(){return draft?draft.exercises.reduce((a,e)=>a+e.sets.length,0):0}
function progress(){const p=$('#progress');if(p){p.max=Math.max(1,total());p.value=count();$('#progressText').textContent=`${count()} / ${total()} sets logged`}}
function start(){if(draft&&!draft.startedAt){draft.startedAt=new Date().toISOString();save();const b=$('#start');if(b){b.textContent='Session in progress';b.disabled=true}}}
function card(e,i){return `<article class="card" data-exercise="${i}"><div class="cardhead"><span class="number">${String(i+1).padStart(2,'0')}</span><div><h3>${esc(e.name)}</h3><small>${esc(e.equipment||'Custom exercise')}</small></div></div>${e.target?`<p class="coach">${esc(e.target)}</p>`:''}<p class="muted">${esc(e.note||'Enter your actual weight and reps, then check each completed set.')}</p><div class="prior">Last time: ${e.prior?.length?e.prior.map(s=>`${esc(s.weight??'—')} ${esc(draft.unit)} × ${esc(s.reps??'—')}`).join(' · '):'No recorded baseline'}</div><div class="sets"><span class="label">SET</span><span class="label">${esc(draft.unit.toUpperCase())}</span><span class="label">REPS</span><span class="label">DONE</span>${e.sets.map((s,j)=>`<span class="muted">${j+1}</span><input aria-label="${esc(e.name)} set ${j+1} weight" type="number" min="0" step="0.1" inputmode="decimal" data-set="${j}" data-field="weight" value="${esc(s.weight)}"><input aria-label="${esc(e.name)} set ${j+1} reps" type="number" min="0" step="1" inputmode="numeric" data-set="${j}" data-field="reps" value="${esc(s.reps)}"><input aria-label="${esc(e.name)} set ${j+1} done" type="checkbox" data-set="${j}" data-field="done" ${s.done?'checked':''}>`).join('')}</div><div class="setactions"><button class="minor" data-action="addset">+ Set</button><button class="minor" data-action="removeset" ${!e.sets.length?'disabled':''}>− Set</button><button class="minor" data-action="rest">Rest ${e.restSeconds||90}s</button></div><div class="fields"><label>Effort / RPE (1–10)<input type="number" min="1" max="10" step="0.5" inputmode="decimal" data-field="rpe" value="${esc(e.rpe)}"></label><label>Pain / discomfort (0–10)<input type="number" min="0" max="10" step="1" inputmode="numeric" data-field="pain" value="${esc(e.pain)}"></label></div><details ${e.substitution||e.notes?'open':''}><summary>Substitution & notes</summary><label>Exercise performed instead<input data-field="substitution" value="${esc(e.substitution)}" placeholder="Leave blank if unchanged"></label><label>Notes<textarea data-field="notes" rows="2" placeholder="Technique, discomfort, assistance…">${esc(e.notes)}</textarea></label><button class="minor danger" data-action="removeexercise">Remove exercise</button></details></article>`}
function renderWorkout(){const root=$('#workout');if(!draft){root.innerHTML=plan?'<h1>Ready for your next session?</h1><p>Your finished workouts are saved in History.</p><button class="primary" id="newSession">Start a fresh session</button>':'<h1>Your gym session</h1><p>No workout is cached yet. Connect once and refresh to load your plan.</p><button id="refresh">Check for workout</button>';return}
root.innerHTML=`<div class="hero"><span class="eyebrow">${draft.startedAt?'IN PROGRESS':'READY WHEN YOU ARE'}</span><h1>${esc(draft.title)}</h1><p class="muted">Change only what’s different. Check each set you complete.</p><div class="actions"><button class="start" id="start" ${draft.startedAt?'disabled':''}>${draft.startedAt?'Session in progress':'Start workout'}</button><button id="refresh">Check for new plan</button></div>${draft.coachNote?`<p class="coach">${esc(draft.coachNote)}</p>`:''}<progress id="progress" max="${Math.max(1,total())}" value="${count()}"></progress><small id="progressText">${count()} / ${total()} sets logged</small></div><div class="exercisegrid">${draft.exercises.map(card).join('')}</div><div class="card"><h3>Add an exercise</h3><div class="fields"><label class="wide">From your gym library<select id="addSelect"><option value="">Choose an exercise…</option>${library.map(e=>`<option value="${esc(e.id)}">${esc(e.name)}</option>`).join('')}</select></label></div><div class="actions"><button id="addLibrary">Add selected</button><button id="showCustom">Custom exercise</button></div><div id="customForm" hidden><label>Exercise name<input id="customName" maxlength="100"></label><button id="addCustom">Add custom exercise</button></div></div><div class="card"><label>Session notes<textarea id="sessionNotes" rows="2" placeholder="How did today feel?">${esc(draft.notes)}</textarea></label><p class="muted">Results stay in this browser. Download a backup after your session.</p><div class="actions"><button class="primary" id="finish">Finish Workout</button><button id="newSession">Start a fresh session</button></div></div>`}
function renderLibrary(filter=''){const q=filter.toLowerCase();$('#library').innerHTML=`<span class="eyebrow">YOUR GYM</span><h1>Exercise library</h1><label class="search">Find an exercise or equipment<input id="search" value="${esc(filter)}" placeholder="Try dumbbells, back, cable…"></label><div class="librarygrid" id="libraryResults">${library.filter(e=>[e.name,e.equipment,e.group].join(' ').toLowerCase().includes(q)).map(e=>`<article class="card"><span class="tag">${esc(e.group)}</span><h3>${esc(e.name)}</h3><p class="muted">${esc(e.equipment)}</p><p>${esc(e.note)}</p><button class="minor" data-add="${esc(e.id)}">Add to workout</button></article>`).join('')}</div><div class="card"><h2>Equipment inventory</h2><p class="muted">${esc(equipment.source||'')}</p>${equipment.items.map(e=>`<p><strong>${esc(e.name)}</strong><br><small>${esc(e.status)}</small></p>`).join('')}</div>`}
function renderHistory(){$('#history').innerHTML=`<span class="eyebrow">YOUR PROGRESS</span><h1>Workout history</h1><p class="muted">Saved on this device. Export a backup to keep results beyond this browser.</p><button id="backup">Download all history</button>${state.history.length?state.history.map((h,i)=>`<article class="card"><small>${esc(new Date(h.finishedAt).toLocaleString())}</small><h3>${esc(h.title)}</h3><p>${h.exercises.reduce((a,e)=>a+e.sets.filter(s=>s.done).length,0)} sets · ${Math.round(h.durationSeconds/60)} min · ${h.exercises.length} exercises</p><button data-result="${i}">View / copy results</button></article>`).join(''):'<p class="empty">Your first finished workout will appear here.</p>'}`}
function render(){renderWorkout();renderLibrary();renderHistory();tick()}
function tab(v){view=v;for(const name of ['workout','library','history'])$('#'+name).hidden=name!==v;document.querySelectorAll('nav button').forEach(b=>{if(b.dataset.tab===v)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')})}
function add(e){if(!draft)fresh();if(!draft)return;const id=draft.exercises.some(x=>x.id===e.id)?e.id+'-'+crypto.randomUUID().slice(0,6):e.id;draft.exercises.push(exercise({...e,id,sets:[{weight:null,reps:null},{weight:null,reps:null},{weight:null,reps:null}],restSeconds:90}));save();renderWorkout();tab('workout');notice(`${e.name} added. Enter your planned or actual sets.`)}
function rest(seconds){restEnd=Date.now()+seconds*1000;save();tick()}
function format(seconds){seconds=Math.max(0,Math.floor(seconds));return `${Math.floor(seconds/60).toString().padStart(2,'0')}:${(seconds%60).toString().padStart(2,'0')}`}
function tick(){$('#elapsed').textContent=format(draft?.startedAt?(Date.now()-Date.parse(draft.startedAt))/1000:0);if(restEnd&&Date.now()>=restEnd){restEnd=0;save();notice('Rest finished. Ready for your next set.');navigator.vibrate?.([150,80,150])}$('#rest').textContent=restEnd?format(Math.ceil((restEnd-Date.now())/1000)):'Ready'}
function showResult(h){result=h;$('#payload').value=JSON.stringify({schemaVersion:1,type:h.type,sessionId:h.sessionId,planId:h.planId,revision:h.revision,title:h.title,unit:h.unit,startedAt:h.startedAt,finishedAt:h.finishedAt,durationSeconds:h.durationSeconds,notes:h.notes,exercises:h.exercises.map(e=>({id:e.id,name:e.name,sets:e.sets,rpe:e.rpe===''?null:Number(e.rpe),pain:e.pain===''?null:Number(e.pain),substitution:e.substitution,notes:e.notes}))});$('#copyStatus').textContent='';$('#resultDialog').showModal()}
function download(data,name){const u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function finish(){if(!count()){notice('Check at least one completed set before finishing.');return}if(!$('#workout').querySelectorAll('input:invalid').length){if(count()<total()&&!confirm(`Save ${count()} completed sets? ${total()-count()} unchecked sets will remain marked incomplete.`))return;const done={schemaVersion:1,type:'coach-chatty-workout-result',...structuredClone(draft),finishedAt:new Date().toISOString(),durationSeconds:Math.max(0,Math.round((Date.now()-Date.parse(draft.startedAt||draft.createdAt))/1000))};state.history.unshift(done);draft=null;restEnd=0;save();render();tab('history');showResult(done);notice(storageOK?'Workout saved on this device. Copy your results to Coach Chatty.':'Storage unavailable. Download these results now.')}else{notice('Fix the highlighted number fields before finishing.');$('#workout').querySelector('input:invalid').reportValidity()}}
async function refresh(user=false){try{const r=await fetch('data/current-workout.json?t='+Date.now(),{cache:'no-store',signal:AbortSignal.timeout(8000)});if(!r.ok)throw Error();const p=validPlan(await r.json());feedFresh=true;const changed=JSON.stringify(p)!==JSON.stringify(plan);plan=p;if(!draft&&!state.history.length)fresh();save();$('#connection').textContent='Plan checked';if(draft&&(draft.planId!==plan.id||draft.revision!==(plan.revision??1)))notice('A new workout is ready. Your current entries are safe; use “Start a fresh session” to load it.');else if(user)notice(changed?(draft?'New plan saved. Your current entries are safe; use “Start a fresh session” to load it.':'New plan ready. Start a fresh session to load it.'):'You have the latest plan.');renderWorkout()}catch{feedFresh=false;$('#connection').textContent=plan?'Cached plan':'Offline';if(user||!plan)notice(plan?'Could not reach the workout feed. Your cached plan and entries are available.':'Connect to load your workout for the first time.')} }
document.addEventListener('input',ev=>{const el=ev.target;if(el.id==='search'){const q=el.value;const pos=el.selectionStart;renderLibrary(q);$('#search').focus();$('#search').setSelectionRange(pos,pos);return}if(el.id==='sessionNotes'){draft.notes=el.value;save();return}const card=el.closest('[data-exercise]');if(!card||!draft||!el.dataset.field)return;const e=draft.exercises[Number(card.dataset.exercise)],k=el.dataset.field;if(el.dataset.set!==undefined){const s=e.sets[Number(el.dataset.set)];if(k==='done'){if(el.checked&&(s.weight===''||s.reps===''||!Number.isFinite(Number(s.weight))||Number(s.weight)<0||!Number.isInteger(Number(s.reps))||Number(s.reps)<0)){el.checked=false;notice('Enter weight (0 for bodyweight) and reps before checking this set.');return}s.done=el.checked;if(s.done)start()}else{s[k]=el.value===''?'':Number(el.value);s.done=false;card.querySelector(`[data-set="${el.dataset.set}"][data-field="done"]`).checked=false}}else e[k]=el.value;save();progress()});
document.addEventListener('click',async ev=>{const b=ev.target.closest('button');if(!b)return;const id=b.id;if(b.dataset.tab){tab(b.dataset.tab);return}if(b.dataset.add){add(library.find(e=>e.id===b.dataset.add));return}if(b.dataset.result!==undefined){showResult(state.history[Number(b.dataset.result)]);return}const c=b.closest('[data-exercise]');if(c&&draft){const i=Number(c.dataset.exercise),e=draft.exercises[i];switch(b.dataset.action){case 'addset':e.sets.push({weight:'',reps:'',done:false});break;case 'removeset':if(e.sets.length&&confirm('Remove the last set and its entries?'))e.sets.pop();break;case 'rest':rest(Number(e.restSeconds)||90);return;case 'removeexercise':if(confirm('Remove this exercise and its entries?'))draft.exercises.splice(i,1);break;default:return}save();renderWorkout();return}
switch(id){case 'start':start();break;case 'refresh':await refresh(true);break;case 'rest60':rest(60);break;case 'rest90':rest(90);break;case 'restStop':restEnd=0;save();tick();break;case 'showCustom':$('#customForm').hidden=false;$('#customName').focus();break;case 'addCustom':{const name=$('#customName').value.trim();if(name)add({id:'custom-'+crypto.randomUUID(),name,equipment:'Custom exercise'});break}case 'addLibrary':{const e=library.find(e=>e.id===$('#addSelect').value);if(e)add(e);break}case 'newSession':if(!plan){notice('Connect to load a workout first.');break}if(draft&&!confirm('Replace the current unfinished session? Finished history is kept.'))break;fresh();renderWorkout();notice('Fresh session ready.');break;case 'finish':finish();break;case 'closeResult':$('#resultDialog').close();break;case 'copyResult':try{await navigator.clipboard.writeText($('#payload').value);$('#copyStatus').textContent='Copied. Paste into your Coach Chatty conversation.'}catch{$('#payload').focus();$('#payload').select();$('#copyStatus').textContent='Select and copy the text above, or download the JSON.'}break;case 'downloadResult':download(result,'coach-chatty-'+result.sessionId+'.json');break;case 'backup':download({schemaVersion:1,history:state.history},'coach-chatty-history.json');break}});
async function init(){if(plan&&!draft&&!state.history.length)fresh();render();await Promise.allSettled([refresh(),...['exercise-library','equipment'].map(async name=>{try{const r=await fetch('data/'+name+'.json',{cache:'no-cache'});if(!r.ok)throw Error();const d=await r.json();if(name==='exercise-library'&&Array.isArray(d))library=d;if(name==='equipment'&&Array.isArray(d.items))equipment=d;save()}catch{}})]);render();if(!draft&&plan){$('#workout').innerHTML='<h1>Ready for your next session?</h1><p>Your last workout is saved in History.</p><button class="primary" id="newSession">Start a fresh session</button>'}if('serviceWorker'in navigator){try{await navigator.serviceWorker.register('sw.js');await navigator.serviceWorker.ready;$('#connection').textContent=feedFresh?'Offline ready':'Cached · offline ready'}catch{notice('Offline installation was unavailable. Keep this page open while training.')}}}window.addEventListener('online',()=>refresh());window.addEventListener('offline',()=>{$('#connection').textContent='Offline'});document.addEventListener('visibilitychange',()=>{if(!document.hidden)tick()});setInterval(tick,1000);init();
